name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Build Docker image
        run: docker build -t steam-scrapper:latest .
      - name: Run unit tests in the container
        run: docker run -it --rm steam-scrapper npm test
      - name: Push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}/steamscrapper:latest
